version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: long
      POSTGRES_PASSWORD: 20031211
      POSTGRES_DB: db_1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

